languaje: node_js
cache:
  directories:
      - ~/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local_dir: dist/
  target-branch: gh-pages
  commit-message: "Deploy Release"
  on:
    branch: master